file:
  upload-path: E:\Year3\CPT202\upload
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.220.16.197:3306/pizza_shop
    username: jcy
    password: root062400

  mail:
    host: smtp.163.com
    username: 18508782239@163.com
    password: KGMTTQVMGTGLEIJN
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/pizza_shop
#  spring.datasource.username=root
#  spring.datasource.password=root062400
#
#
#
#
#
#  spring.mail.host=smtp.163.com
#  spring.mail.username=18508782239@163.com
#  spring.mail.password=KGMTTQVMGTGLEIJN
#  spring.mail.properties
#
#
#  server.servlet.context-path=/pizza_shop
#
#  mybatis.mapper-locations=classpath:/mappers/*.xml
#  mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
server:
  servlet:
    context-path: /pizza_shop


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  logging:
    level:
      com.example.pizza_order_demo.mapper: debug
  type-aliases-package: com.example.pizza_order_demo.model
  mapper-locations: classpath*:/mappers/*Mapper.xml
#  mybatis.configuration.map-underscore-to-camel-case=true