package com.example.pizza_order_demo.model;

public class Coupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.func
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long func;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.duration
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.start_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.end_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.sell_price
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer sellPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.id
     *
     * @return the value of t_coupon.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.id
     *
     * @param id the value for t_coupon.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.type
     *
     * @return the value of t_coupon.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.type
     *
     * @param type the value for t_coupon.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.func
     *
     * @return the value of t_coupon.func
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getFunc() {
        return func;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.func
     *
     * @param func the value for t_coupon.func
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setFunc(Long func) {
        this.func = func;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.duration
     *
     * @return the value of t_coupon.duration
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.duration
     *
     * @param duration the value for t_coupon.duration
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.start_time
     *
     * @return the value of t_coupon.start_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.start_time
     *
     * @param startTime the value for t_coupon.start_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.end_time
     *
     * @return the value of t_coupon.end_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.end_time
     *
     * @param endTime the value for t_coupon.end_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.sell_price
     *
     * @return the value of t_coupon.sell_price
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.sell_price
     *
     * @param sellPrice the value for t_coupon.sell_price
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setSellPrice(Integer sellPrice) {
        this.sellPrice = sellPrice;
    }
}