package com.example.pizza_order_demo.model;

public class Deliveryman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliveryman.id
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliveryman.deliveryman_name
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    private String deliverymanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliveryman.phone
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliveryman.deleted
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliveryman.id
     *
     * @return the value of t_deliveryman.id
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliveryman.id
     *
     * @param id the value for t_deliveryman.id
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliveryman.deliveryman_name
     *
     * @return the value of t_deliveryman.deliveryman_name
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public String getDeliverymanName() {
        return deliverymanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliveryman.deliveryman_name
     *
     * @param deliverymanName the value for t_deliveryman.deliveryman_name
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public void setDeliverymanName(String deliverymanName) {
        this.deliverymanName = deliverymanName == null ? null : deliverymanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliveryman.phone
     *
     * @return the value of t_deliveryman.phone
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliveryman.phone
     *
     * @param phone the value for t_deliveryman.phone
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliveryman.deleted
     *
     * @return the value of t_deliveryman.deleted
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliveryman.deleted
     *
     * @param deleted the value for t_deliveryman.deleted
     *
     * @mbg.generated Tue Apr 25 17:33:51 CST 2023
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}