package com.example.pizza_order_demo.model;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.description
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.create_time
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.is_handled
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private Integer isHandled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.user_name
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operationType
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    private Integer operationtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.description
     *
     * @return the value of t_log.description
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.description
     *
     * @param description the value for t_log.description
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.create_time
     *
     * @return the value of t_log.create_time
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.create_time
     *
     * @param createTime the value for t_log.create_time
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.is_handled
     *
     * @return the value of t_log.is_handled
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public Integer getIsHandled() {
        return isHandled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.is_handled
     *
     * @param isHandled the value for t_log.is_handled
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setIsHandled(Integer isHandled) {
        this.isHandled = isHandled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.user_name
     *
     * @return the value of t_log.user_name
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.user_name
     *
     * @param userName the value for t_log.user_name
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operationType
     *
     * @return the value of t_log.operationType
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public Integer getOperationtype() {
        return operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operationType
     *
     * @param operationtype the value for t_log.operationType
     *
     * @mbg.generated Mon Apr 24 18:38:25 CST 2023
     */
    public void setOperationtype(Integer operationtype) {
        this.operationtype = operationtype;
    }
}