package com.example.pizza_order_demo.model;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.create_time
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.is_handled
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer isHandled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.file_path
     *
     * @return the value of t_log.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.file_path
     *
     * @param filePath the value for t_log.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.create_time
     *
     * @return the value of t_log.create_time
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.create_time
     *
     * @param createTime the value for t_log.create_time
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.is_handled
     *
     * @return the value of t_log.is_handled
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getIsHandled() {
        return isHandled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.is_handled
     *
     * @param isHandled the value for t_log.is_handled
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setIsHandled(Integer isHandled) {
        this.isHandled = isHandled;
    }
}