package com.example.pizza_order_demo.model;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.dish_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer dishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.order_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String flavour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.number
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.total_price
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.size
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.id
     *
     * @return the value of t_order_detail.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.id
     *
     * @param id the value for t_order_detail.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.dish_id
     *
     * @return the value of t_order_detail.dish_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.dish_id
     *
     * @param dishId the value for t_order_detail.dish_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.order_id
     *
     * @return the value of t_order_detail.order_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.order_id
     *
     * @param orderId the value for t_order_detail.order_id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.flavour
     *
     * @return the value of t_order_detail.flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getFlavour() {
        return flavour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.flavour
     *
     * @param flavour the value for t_order_detail.flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setFlavour(String flavour) {
        this.flavour = flavour == null ? null : flavour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.number
     *
     * @return the value of t_order_detail.number
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.number
     *
     * @param number the value for t_order_detail.number
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.status
     *
     * @return the value of t_order_detail.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.status
     *
     * @param status the value for t_order_detail.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.total_price
     *
     * @return the value of t_order_detail.total_price
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.total_price
     *
     * @param totalPrice the value for t_order_detail.total_price
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.size
     *
     * @return the value of t_order_detail.size
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.size
     *
     * @param size the value for t_order_detail.size
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setSize(Integer size) {
        this.size = size;
    }
}