package com.example.pizza_order_demo.model;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.dish_name
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private String dishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.order_id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.topping
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private String topping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.amount
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.state
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.total_price
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private Integer totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.size
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.imgs
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    private String imgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.id
     *
     * @return the value of t_order_detail.id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.id
     *
     * @param id the value for t_order_detail.id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.dish_name
     *
     * @return the value of t_order_detail.dish_name
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public String getDishName() {
        return dishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.dish_name
     *
     * @param dishName the value for t_order_detail.dish_name
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setDishName(String dishName) {
        this.dishName = dishName == null ? null : dishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.order_id
     *
     * @return the value of t_order_detail.order_id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.order_id
     *
     * @param orderId the value for t_order_detail.order_id
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.topping
     *
     * @return the value of t_order_detail.topping
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public String getTopping() {
        return topping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.topping
     *
     * @param topping the value for t_order_detail.topping
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setTopping(String topping) {
        this.topping = topping == null ? null : topping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.amount
     *
     * @return the value of t_order_detail.amount
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.amount
     *
     * @param amount the value for t_order_detail.amount
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.state
     *
     * @return the value of t_order_detail.state
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.state
     *
     * @param state the value for t_order_detail.state
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.total_price
     *
     * @return the value of t_order_detail.total_price
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.total_price
     *
     * @param totalPrice the value for t_order_detail.total_price
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.size
     *
     * @return the value of t_order_detail.size
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.size
     *
     * @param size the value for t_order_detail.size
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.imgs
     *
     * @return the value of t_order_detail.imgs
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.imgs
     *
     * @param imgs the value for t_order_detail.imgs
     *
     * @mbg.generated Fri Apr 21 20:24:54 CST 2023
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }
}