package com.example.pizza_order_demo.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_address_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer userAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.state
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.deliveryman_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer deliverymanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pickup_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Long pickupTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_address_id
     *
     * @return the value of t_order.user_address_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getUserAddressId() {
        return userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_address_id
     *
     * @param userAddressId the value for t_order.user_address_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setUserAddressId(Integer userAddressId) {
        this.userAddressId = userAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.state
     *
     * @return the value of t_order.state
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.state
     *
     * @param state the value for t_order.state
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.type
     *
     * @return the value of t_order.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.type
     *
     * @param type the value for t_order.type
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.deliveryman_id
     *
     * @return the value of t_order.deliveryman_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getDeliverymanId() {
        return deliverymanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.deliveryman_id
     *
     * @param deliverymanId the value for t_order.deliveryman_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setDeliverymanId(Integer deliverymanId) {
        this.deliverymanId = deliverymanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pickup_time
     *
     * @return the value of t_order.pickup_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Long getPickupTime() {
        return pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pickup_time
     *
     * @param pickupTime the value for t_order.pickup_time
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setPickupTime(Long pickupTime) {
        this.pickupTime = pickupTime;
    }
}