package com.example.pizza_order_demo.model;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.price
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.order_id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment.create_time
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.id
     *
     * @return the value of t_payment.id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.id
     *
     * @param id the value for t_payment.id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.price
     *
     * @return the value of t_payment.price
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.price
     *
     * @param price the value for t_payment.price
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.order_id
     *
     * @return the value of t_payment.order_id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.order_id
     *
     * @param orderId the value for t_payment.order_id
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment.create_time
     *
     * @return the value of t_payment.create_time
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment.create_time
     *
     * @param createTime the value for t_payment.create_time
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}