package com.example.pizza_order_demo.model;

public class Plan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan.file_name
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.id
     *
     * @return the value of t_plan.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.id
     *
     * @param id the value for t_plan.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.file_path
     *
     * @return the value of t_plan.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.file_path
     *
     * @param filePath the value for t_plan.file_path
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan.file_name
     *
     * @return the value of t_plan.file_name
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan.file_name
     *
     * @param fileName the value for t_plan.file_name
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}