package com.example.pizza_order_demo.model;

public class ShoppingRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.user_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.dish_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private Integer dishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.topping_detail
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private String toppingDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.number
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.is_valid
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.id
     *
     * @return the value of shopping_record.id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.id
     *
     * @param id the value for shopping_record.id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.user_id
     *
     * @return the value of shopping_record.user_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.user_id
     *
     * @param userId the value for shopping_record.user_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.dish_id
     *
     * @return the value of shopping_record.dish_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.dish_id
     *
     * @param dishId the value for shopping_record.dish_id
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.topping_detail
     *
     * @return the value of shopping_record.topping_detail
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public String getToppingDetail() {
        return toppingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.topping_detail
     *
     * @param toppingDetail the value for shopping_record.topping_detail
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setToppingDetail(String toppingDetail) {
        this.toppingDetail = toppingDetail == null ? null : toppingDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.number
     *
     * @return the value of shopping_record.number
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.number
     *
     * @param number the value for shopping_record.number
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.is_valid
     *
     * @return the value of shopping_record.is_valid
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.is_valid
     *
     * @param isValid the value for shopping_record.is_valid
     *
     * @mbg.generated Fri Apr 14 15:01:02 CST 2023
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}