package com.example.pizza_order_demo.model;

public class ShoppingRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.dish_name
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private String dishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.topping_detail
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private String toppingDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.amount
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.is_valid
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_record.size
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.id
     *
     * @return the value of shopping_record.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.id
     *
     * @param id the value for shopping_record.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.user_id
     *
     * @return the value of shopping_record.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.user_id
     *
     * @param userId the value for shopping_record.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.dish_name
     *
     * @return the value of shopping_record.dish_name
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public String getDishName() {
        return dishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.dish_name
     *
     * @param dishName the value for shopping_record.dish_name
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setDishName(String dishName) {
        this.dishName = dishName == null ? null : dishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.topping_detail
     *
     * @return the value of shopping_record.topping_detail
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public String getToppingDetail() {
        return toppingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.topping_detail
     *
     * @param toppingDetail the value for shopping_record.topping_detail
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setToppingDetail(String toppingDetail) {
        this.toppingDetail = toppingDetail == null ? null : toppingDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.amount
     *
     * @return the value of shopping_record.amount
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.amount
     *
     * @param amount the value for shopping_record.amount
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.is_valid
     *
     * @return the value of shopping_record.is_valid
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.is_valid
     *
     * @param isValid the value for shopping_record.is_valid
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_record.size
     *
     * @return the value of shopping_record.size
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_record.size
     *
     * @param size the value for shopping_record.size
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}