package com.example.pizza_order_demo.model;

public class Topping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topping.id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topping.dish_id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    private Integer dishId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topping.topping_name
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    private String toppingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topping.price
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topping.deleted
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topping.id
     *
     * @return the value of t_topping.id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topping.id
     *
     * @param id the value for t_topping.id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topping.dish_id
     *
     * @return the value of t_topping.dish_id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topping.dish_id
     *
     * @param dishId the value for t_topping.dish_id
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topping.topping_name
     *
     * @return the value of t_topping.topping_name
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public String getToppingName() {
        return toppingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topping.topping_name
     *
     * @param toppingName the value for t_topping.topping_name
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public void setToppingName(String toppingName) {
        this.toppingName = toppingName == null ? null : toppingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topping.price
     *
     * @return the value of t_topping.price
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topping.price
     *
     * @param price the value for t_topping.price
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topping.deleted
     *
     * @return the value of t_topping.deleted
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topping.deleted
     *
     * @param deleted the value for t_topping.deleted
     *
     * @mbg.generated Sun Apr 16 20:46:06 CST 2023
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}