package com.example.pizza_order_demo.model;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.location
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.phone
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.id
     *
     * @return the value of t_user_address.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.id
     *
     * @param id the value for t_user_address.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.user_id
     *
     * @return the value of t_user_address.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.user_id
     *
     * @param userId the value for t_user_address.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.location
     *
     * @return the value of t_user_address.location
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.location
     *
     * @param location the value for t_user_address.location
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.phone
     *
     * @return the value of t_user_address.phone
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.phone
     *
     * @param phone the value for t_user_address.phone
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}