package com.example.pizza_order_demo.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.pwd
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.safe_question
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String safeQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.answer
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mail
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    private String mail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.pwd
     *
     * @return the value of t_user.pwd
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.pwd
     *
     * @param pwd the value for t_user.pwd
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.safe_question
     *
     * @return the value of t_user.safe_question
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getSafeQuestion() {
        return safeQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.safe_question
     *
     * @param safeQuestion the value for t_user.safe_question
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setSafeQuestion(String safeQuestion) {
        this.safeQuestion = safeQuestion == null ? null : safeQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.answer
     *
     * @return the value of t_user.answer
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.answer
     *
     * @param answer the value for t_user.answer
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mail
     *
     * @return the value of t_user.mail
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mail
     *
     * @param mail the value for t_user.mail
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }
}