package com.example.pizza_order_demo.model;

public class Wallet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.id
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.username
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.balance
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.id
     *
     * @return the value of t_wallet.id
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.id
     *
     * @param id the value for t_wallet.id
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.username
     *
     * @return the value of t_wallet.username
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.username
     *
     * @param username the value for t_wallet.username
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.balance
     *
     * @return the value of t_wallet.balance
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.balance
     *
     * @param balance the value for t_wallet.balance
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}