package com.example.pizza_order_demo.model;

public class Wallet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wallet.balance
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.id
     *
     * @return the value of t_wallet.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.id
     *
     * @param id the value for t_wallet.id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.user_id
     *
     * @return the value of t_wallet.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.user_id
     *
     * @param userId the value for t_wallet.user_id
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wallet.balance
     *
     * @return the value of t_wallet.balance
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wallet.balance
     *
     * @param balance the value for t_wallet.balance
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}