package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.Deliveryman;
import com.example.pizza_order_demo.model.DeliverymanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeliverymanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    long countByExample(DeliverymanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int deleteByExample(DeliverymanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int insert(Deliveryman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int insertSelective(Deliveryman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    List<Deliveryman> selectByExample(DeliverymanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    Deliveryman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByExampleSelective(@Param("record") Deliveryman record, @Param("example") DeliverymanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByExample(@Param("record") Deliveryman record, @Param("example") DeliverymanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByPrimaryKeySelective(Deliveryman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deliveryman
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByPrimaryKey(Deliveryman record);
}