package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.Dish;
import com.example.pizza_order_demo.model.DishExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    long countByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int deleteByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int insertSelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    List<Dish> selectByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    Dish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByExampleSelective(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByExample(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByPrimaryKeySelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dish
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByPrimaryKey(Dish record);
}