package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.Flavour;
import com.example.pizza_order_demo.model.FlavourExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface FlavourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    long countByExample(FlavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int deleteByExample(FlavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int insert(Flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int insertSelective(Flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    List<Flavour> selectByExample(FlavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    Flavour selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByExampleSelective(@Param("record") Flavour record, @Param("example") FlavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByExample(@Param("record") Flavour record, @Param("example") FlavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByPrimaryKeySelective(Flavour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flavour
     *
     * @mbg.generated Wed Apr 05 17:40:03 CST 2023
     */
    int updateByPrimaryKey(Flavour record);
}