package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.Payment;
import com.example.pizza_order_demo.model.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    long countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int insert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    Payment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int updateByExampleSelective(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int updateByExample(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int updateByPrimaryKeySelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment
     *
     * @mbg.generated Sat Apr 22 16:59:55 CST 2023
     */
    int updateByPrimaryKey(Payment record);
}