package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.ShoppingRecord;
import com.example.pizza_order_demo.model.ShoppingRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    long countByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int deleteByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int insert(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int insertSelective(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    List<ShoppingRecord> selectByExample(ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    ShoppingRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShoppingRecord record, @Param("example") ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByExample(@Param("record") ShoppingRecord record, @Param("example") ShoppingRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByPrimaryKeySelective(ShoppingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_record
     *
     * @mbg.generated Sat Apr 15 17:25:54 CST 2023
     */
    int updateByPrimaryKey(ShoppingRecord record);
}