package com.example.pizza_order_demo.mapper;

import com.example.pizza_order_demo.model.Wallet;
import com.example.pizza_order_demo.model.WalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    long countByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int deleteByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    List<Wallet> selectByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    Wallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int updateByExampleSelective(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int updateByExample(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wallet
     *
     * @mbg.generated Wed Apr 26 13:53:21 CST 2023
     */
    int updateByPrimaryKey(Wallet record);
}